name: Publish to PyPI and GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## What's New in ${{ github.ref_name }}
            ### New Features
            - **Comprehensive Type Hints**: Added complete type annotations to all methods and functions
            - Enhanced IDE support with better autocomplete and error detection
            - Improved code documentation through type annotations
            - MyPy compatibility for static type checking
            - Better developer experience and code maintainability

            ### Improvements
            - Updated dependency management with complete requirements specification
            - Enhanced null safety with proper error handling
            - Improved code quality and professional standards
            - Full backward compatibility maintained

            ### Dependencies
            - Updated requirements.txt with scipy and tqdm dependencies
            - Synchronized dependency versions across setup.py and requirements.txt

            ## Installation
            ```
            pip install outlier-cleaner==${{ github.ref_name }}
            ```

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
