name: Publish to PyPI and GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## What's New in ${{ github.ref_name }}

          ### Changes
          - Fixed author name spelling to "Subashanan Nair"
          - Updated version number
          - Improved release workflow configuration

          ### Previous Updates
          - Enhanced outlier indices tracking in all removal methods
          - Improved `get_outlier_indices()` to handle missing columns gracefully
          - Optimized outlier statistics calculation
          - Removed redundant outlier indices from `get_outlier_stats()` output
          - Added detailed changelog section to README
          - Improved method descriptions and documentation

          ## Installation
          ```bash
          pip install outlier-cleaner==${{ github.ref_name }}
          ```
    - name: Build and publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine upload dist/* 